🎨 Format `bin/test`
Makes it a bit more readable

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -5,13 +5,26 @@
 # This script contains all the test commands for this app, which will be run
 # on the continuous integration server.
 if [ "$ELIXIR_VERSION" != "1.11.3" ]; then
-MIX_ENV=test mix format --check-formatted || { echo 'Code was not formatted!'; exit 1; }
+	MIX_ENV=test mix format --check-formatted || {
+		echo 'Code was not formatted!'
+		exit 1
+	}
 fi
 
-MIX_ENV=test mix compile --force --warnings-as-errors || { echo 'Please fix all compiler warnings.'; exit 1; }
+MIX_ENV=test mix compile --force --warnings-as-errors || {
+	echo 'Please fix all compiler warnings.'
+	exit 1
+}
 
 if [ ! $CI ]; then
-  MIX_ENV=test mix test || { echo 'Tests failed!'; exit 1; }
+	MIX_ENV=test mix test || {
+		echo 'Tests failed!'
+		exit 1
+	}
 else
-  MIX_ENV=test mix coveralls.semaphore || { echo 'Tests failed!'; exit 1; }
+	MIX_ENV=test mix coveralls.semaphore || {
+		echo 'Tests failed!'
+		exit 1
+	}
 fi
+
